// content_quotes.cpp — the DECRYPTOGRAM quote pool. One row per quote; see
// content_quotes.h for the field schema, the two rules a row must pass, and the wire
// number discipline.

#include "core/content/content_quotes.h"

#include "core/content/content_achievements.h"

namespace mal {

namespace {

const QuoteDef kQuotes[] = {
    {1, "ANY SUFFICIENTLY ADVANCED TECHNOLOGY IS EQUIVALENT TO MAGIC.",
     "ARTHUR C. CLARKE"},
    {2, "TECHNOLOGY IS ANYTHING THAT WASN'T AROUND WHEN YOU WERE BORN.", "ALAN KAY"},
    {3, "MACHINES TAKE ME BY SURPRISE WITH GREAT FREQUENCY.", "ALAN TURING"},
    {4, "THOSE WHO CAN IMAGINE ANYTHING, CAN CREATE THE IMPOSSIBLE.", "ALAN TURING"},
    {5, "IF A MACHINE IS EXPECTED TO BE INFALLIBLE, IT CANNOT ALSO BE INTELLIGENT.",
     "ALAN TURING"},

    // Gated, and the two gates are the whole point of the field: a quote about seeing
    // further than you have gone waits on the dive that proves you have, and a quote
    // about forgiveness over permission waits on the run that took it.
    {6, "WE CAN ONLY SEE A SHORT DISTANCE AHEAD, BUT WE CAN SEE PLENTY THERE THAT NEEDS TO BE DONE.",
     "ALAN TURING", ach::kDeepWebDepth8},
    {7, "IF IT'S A GOOD IDEA, GO AHEAD AND DO IT.", "GRACE HOPPER", ach::kGoneRogue},

    {8, "ANYONE WHO HAS NEVER MADE A MISTAKE HAS NEVER TRIED ANYTHING NEW.",
     "ALBERT EINSTEIN"},
    {9, "LOGIC WILL GET YOU FROM A TO Z; IMAGINATION WILL GET YOU EVERYWHERE.",
     "ALBERT EINSTEIN"},
    {10, "IF YOU CAN'T EXPLAIN IT TO A SIX YEAR OLD, YOU DON'T UNDERSTAND IT YOURSELF.",
     "ALBERT EINSTEIN"},
    {11, "LIFE IS LIKE RIDING A BICYCLE. TO KEEP YOUR BALANCE, YOU MUST KEEP MOVING.",
     "ALBERT EINSTEIN"},
    {12, "IT HAS BECOME APPALLINGLY OBVIOUS THAT OUR TECHNOLOGY HAS EXCEEDED OUR HUMANITY.",
     "ALBERT EINSTEIN"},
    {13, "A PROGRAM THAT HAS NOT BEEN TESTED DOES NOT WORK.", "BJARNE STROUSTRUP"},
    {14, "PRIVACY IS AN INHERENT HUMAN RIGHT, AND A REQUIREMENT FOR HUMAN DIGNITY.",
     "BRUCE SCHNEIER"},
    {15, "IT IS POOR CIVIC HYGIENE TO INSTALL TECHNOLOGIES THAT COULD SOMEDAY FACILITATE A POLICE STATE.",
     "BRUCE SCHNEIER"},
    {16, "A BRILLIANT SOLUTION TO THE WRONG PROBLEM CAN BE WORSE THAN NO SOLUTION AT ALL.",
     "DON NORMAN"},
    {17, "WALKING ON WATER AND DEVELOPING SOFTWARE FROM A SPECIFICATION ARE EASY IF BOTH ARE FROZEN.",
     "EDWARD V. BERARD"},
    {18, "ONE MACHINE CAN DO THE WORK OF FIFTY ORDINARY MEN.", "ELBERT HUBBARD"},
    {19, "THE INTERNET IS BECOMING THE TOWN SQUARE FOR THE GLOBAL VILLAGE OF TOMORROW.",
     "BILL GATES"},
    {20, "YOUR MOST UNHAPPY CUSTOMERS ARE YOUR GREATEST SOURCE OF LEARNING.", "BILL GATES"},
    {21, "PROGRAMS MUST BE WRITTEN FOR PEOPLE TO READ, AND ONLY INCIDENTALLY FOR MACHINES TO EXECUTE.",
     "HAROLD ABELSON"},
    {22, "HARDWARE: THE PARTS OF A COMPUTER THAT CAN BE KICKED.", "JEFF PESIS"},
    {23, "IT DOESN'T MATTER WHAT YOU KNOW, WHAT MATTERS IS WHEN YOU KNOW.", "KATHY SIERRA"},
    {24, "PERL - THE ONLY LANGUAGE THAT LOOKS THE SAME BEFORE AND AFTER RSA ENCRYPTION.",
     "KEITH BOSTIC"},
    {25, "ONE OF MY MOST PRODUCTIVE DAYS WAS THROWING AWAY 1000 LINES OF CODE.",
     "KEN THOMPSON"},
    {26, "IT IS EASIER TO PORT A SHELL THAN A SHELL SCRIPT.", "LARRY WALL"},
    {27, "TALK IS CHEAP. SHOW ME THE CODE.", "LINUS TORVALDS"},
    {28, "COMPUTERS ARE USELESS. THEY CAN ONLY GIVE YOU ANSWERS.", "PABLO PICASSO"},
    {29, "TO ITERATE IS HUMAN, TO RECURSE DIVINE.", "PETER DEUTSCH"},
    {30, "INNOVATION DISTINGUISHES BETWEEN A LEADER AND A FOLLOWER.", "STEVE JOBS"},
    {31, "GOOD CODE IS ITS OWN BEST DOCUMENTATION.", "STEVE MCCONNELL"},
    {32, "I DON'T CARE IF IT WORKS ON YOUR MACHINE! WE ARE NOT SHIPPING YOUR MACHINE!",
     "VIDIU PLATON"},
    {33, "FAILURE IS AN OPTION HERE. IF THINGS ARE NOT FAILING, YOU ARE NOT INNOVATING ENOUGH.",
     "ELON MUSK"},
    {34, "THE REAL DANGER IS NOT THAT COMPUTERS WILL THINK LIKE MEN, BUT THAT MEN WILL THINK LIKE COMPUTERS.",
     "SYDNEY HARRIS"},
};

}  // namespace

const QuoteDef* quotes() { return kQuotes; }

int quoteCount() { return static_cast<int>(sizeof(kQuotes) / sizeof(kQuotes[0])); }

int quoteIndexByWire(int wire) {
    for (int i = 0; i < quoteCount(); ++i)
        if (kQuotes[i].wire == wire) return i;
    return -1;
}

QuoteReward quoteWinReward() {
    return {QuoteReward::Kind::RigGrant, 1, "bandwidth"};
}

}  // namespace mal
