// content_recipes.cpp — the MERGE HUB recipe rows.
//
// One content table (see content_recipes.h for the shape, the wire discipline, and who
// reads it). Edit rows here; adding one is this row plus its output dish on
// content_quotes.h's prize ladder, since a recipe missing from the ladder is one
// nothing can hand over.
#include "core/content/content_recipes.h"

namespace mal {

const MergeRecipe kMergeRecipes[] = {
    {"Pwnzu-Patched Noodles", {{"null_noodles", 1}, {"pwnzu_sauce", 1}},
     "pwnzu_patched_noodles", 1, /*wire=*/0, "MERGED PATCHED NOODLES"},
    {"Fully-Stacked Nachos", {{"tortilla_chip", 1}, {"osi_dip", 1}},
     "fully_stacked_nachos", 1, /*wire=*/1, "MERGED STACKED NACHOS"},
    // The pantry's own two: a four-ingredient base dish, then a one-ingredient pass
    // back through the pan that turns it into the better version of itself. Both are
    // stocked at Moor-to-Moor, which is why both carry the met-the-dish gate.
    {"Hashed Browns",
     {{"c_salt", 1}, {"grepsed_oil", 1}, {"cronstarch", 1}, {"polltatoes", 1}},
     "hashed_browns", 1, /*wire=*/2, "MERGED HASHED BROWNS",
     {"hashed_browns", "salted_hashed_browns"}},
    {"Salted&Hashed Browns", {{"c_salt", 1}, {"hashed_browns", 1}},
     "salted_hashed_browns", 1, /*wire=*/3, "MERGED SALTED BROWNS",
     {"hashed_browns", "salted_hashed_browns"}},
    // The rest of the pantry, cooked. Between them these use every staple but Spoiled
    // Macrol (which is Pier-to-Peer's currency, not an ingredient), so no shelf of the
    // pantry is only ever eaten raw. Quantities are the point of each row as much as the
    // ids are: a dish that wants four Spam is a dish that clears the folder.
    {"Cracquettes",
     {{"spam", 4}, {"breadcrumbs", 2}, {"regeggs", 1}, {"grepsed_oil", 1}},
     "cracquettes", 1, /*wire=*/4, "MERGED CRACQUETTES"},
    {"Hackshuka",
     {{"regeggs", 2}, {"data_leek", 1}, {"boolean_cubes", 1}, {"c_salt", 1}},
     "hackshuka", 1, /*wire=*/5, "MERGED HACKSHUKA"},
    {"Applet Turnover",
     {{"applets", 2}, {"syntactic_sugar", 1}, {"cronstarch", 1}, {"vanilla_extract", 1}},
     "applet_turnover", 1, /*wire=*/6, "MERGED APPLET TURNOVER"},
    {"Serial Bar",
     {{"universal_cereal_box", 1}, {"breadcrumbs", 2}, {"syntactic_sugar", 1},
      {"boolean_cubes", 1}},
     "serial_bar", 1, /*wire=*/7, "MERGED SERIAL BAR"},
    {"Macrol Fry-Up",
     {{"fresh_macrol", 2}, {"grepsed_oil", 1}, {"breadcrumbs", 1}, {"c_salt", 1}},
     "macrol_fry_up", 1, /*wire=*/8, "MERGED MACROL FRY-UP"},
    {"Vanilla Java Roast",
     {{"java", 2}, {"syntactic_sugar", 1}, {"vanilla_extract", 1}, {"kernel_oil", 1}},
     "vanilla_java_roast", 1, /*wire=*/9, "MERGED JAVA ROAST"},
    {"GNUlash",
     {{"root_veg", 1}, {"kernel_oil", 1}, {"polltatoes", 2},
      {"desalinated_c_salt", 1}},
     "gnulash", 1, /*wire=*/10, "MERGED GNULASH"},
    // The second service. Three of these are the ingredient's own joke finished:
    // Boolean Cubes ARE a risotto's stock, OSI Dip's seven layers ARE the lasagne, and
    // a RAMen bowl is exactly noodles, egg and leek.
    {"RISCotto",
     {{"boolean_cubes", 2}, {"root_veg", 1}, {"kernel_oil", 1}, {"c_salt", 1}},
     "riscotto", 1, /*wire=*/11, "MERGED RISCOTTO"},
    {"LANsagne",
     {{"osi_dip", 1}, {"null_noodles", 2}, {"pwnzu_sauce", 1}, {"c_salt", 1}},
     "lansagne", 1, /*wire=*/12, "MERGED LANSAGNE"},
    {"RAMen",
     {{"null_noodles", 2}, {"regeggs", 1}, {"data_leek", 1}, {"kernel_oil", 1}},
     "ramen", 1, /*wire=*/13, "MERGED RAMEN"},
    {"Tiramisudo",
     {{"java", 2}, {"syntactic_sugar", 1}, {"breadcrumbs", 2},
      {"vanilla_extract", 1}},
     "tiramisudo", 1, /*wire=*/14, "MERGED TIRAMISUDO"},
    {"Core Dumplings",
     {{"cronstarch", 2}, {"spam", 2}, {"data_leek", 1}, {"c_salt", 1}},
     "core_dumplings", 1, /*wire=*/15, "MERGED CORE DUMPLINGS"},
    {"Forkaccia",
     {{"cronstarch", 2}, {"grepsed_oil", 1}, {"breadcrumbs", 2}, {"c_salt", 1}},
     "forkaccia", 1, /*wire=*/16, "MERGED FORKACCIA"},
    // The first recipe whose lead ingredient is another DISH. Nothing new was needed
    // to express it — an input id is an item id, and a cooked dish is an item — which
    // is the point: the pantry can now stack without a second mechanism.
    {"Cacherole",
     {{"hashed_browns", 1}, {"spam", 2}, {"boolean_cubes", 1}, {"grepsed_oil", 1}},
     "cacherole", 1, /*wire=*/17, "MERGED CACHEROLE"},
    // The third service, which spends the last of kMergeRecipeWireCap. Two rows are
    // the method itself rather than an upgrade: Portridge cooks one Bootmeal into the
    // same bowl at the same tier, and Recursive Turducken is three of one bird — an
    // input QUANTITY, not three ingredients, so the base case is the ingredient.
    {"Portridge", {{"bootmeal", 1}},
     "portridge", 1, /*wire=*/18, "MERGED PORTRIDGE"},
    {"Halloumi, World", {{"cruds", 2}, {"c_salt", 1}},
     "halloumi_world", 1, /*wire=*/19, "MERGED HALLOUMI WORLD"},
    {"NaN Bread",
     {{"self_signed_flour", 2}, {"c_salt", 1}, {"grepsed_oil", 1}},
     "nan_bread", 1, /*wire=*/20, "MERGED NAN BREAD"},
    // Second-order, like Cacherole: the loaf it wants is another dish off this table.
    {"Chrootons",
     {{"nan_bread", 1}, {"grepsed_oil", 1}, {"c_salt", 1}},
     "chrootons", 1, /*wire=*/21, "MERGED CHROOTONS"},
    {"Gzipacho",
     {{"bytesteak_tomatoes", 2}, {"gherkins", 1}, {"breadcrumbs", 2},
      {"grepsed_oil", 1}},
     "gzipacho", 1, /*wire=*/22, "MERGED GZIPACHO"},
    // Honeypot Yogurt is deliberately absent — a lassi's one missing ingredient, and
    // the dish's own description names everything here and nothing else.
    {"Lossy Lassi",
     {{"papaya", 2}, {"syntactic_sugar", 1}, {"c_salt", 1}},
     "lossy_lassi", 1, /*wire=*/23, "MERGED LOSSY LASSI"},
    {"Cod Review",
     {{"red_herring", 2}, {"self_signed_flour", 1}, {"grepsed_oil", 1}},
     "cod_review", 1, /*wire=*/24, "MERGED COD REVIEW"},
    {"Recursive Turducken", {{"rubber_ducks", 3}, {"c_salt", 1}},
     "recursive_turducken", 1, /*wire=*/25, "MERGED TURDUCKEN"},
    {"Peking Duck Typing",
     {{"rubber_ducks", 1}, {"imaple_syrup", 1}, {"shellots", 2},
      {"cronstarch", 1}},
     "peking_duck_typing", 1, /*wire=*/26, "MERGED DUCK TYPING"},
    {"Semaphreddo",
     {{"double_precision_cream", 2}, {"syntactic_sugar", 1}, {"cocoa", 1}},
     "semaphreddo", 1, /*wire=*/27, "MERGED SEMAPHREDDO"},
    {"Spaghetti Code",
     {{"linkguine", 2}, {"bytesteak_tomatoes", 2}, {"garlic_escapes", 1},
      {"grepsed_oil", 1}},
     "spaghetti_code", 1, /*wire=*/28, "MERGED SPAGHETTI CODE"},
    {"Emacsaroni",
     {{"linkguine", 2}, {"mozillarella", 2}, {"churned_butter", 1}},
     "emacsaroni", 1, /*wire=*/29, "MERGED EMACSARONI"},
    {"Bisectuits",
     {{"self_signed_flour", 2}, {"churned_butter", 1}, {"syntactic_sugar", 1}},
     "bisectuits", 1, /*wire=*/30, "MERGED BISECTUITS"},
    {"Quicksortbet",
     {{"grepefruit", 2}, {"honeypot_yogurt", 1}, {"syntactic_sugar", 1}},
     "quicksortbet", 1, /*wire=*/31, "MERGED QUICKSORTBET"},
    // The fourth service — the rest of the kitchen, grouped the way the item table
    // groups it. Every staple on the pantry's three shelves is named by at least one
    // row here, so nothing is only ever eaten raw. Four rows are second-order (their
    // lead ingredient is another dish): Crostini and Kernel Panini want a Buguette,
    // Payloaf wants a NaN Bread, and Disk Platter wants a Crostini.
    {"Buguette", {{"self_signed_flour", 3}, {"c_salt", 1}},
     "buguette", 1, /*wire=*/32, "MERGED BUGUETTE"},
    {"CHAPati",
     {{"self_signed_flour", 2}, {"churned_butter", 1}, {"c_salt", 1}},
     "chapati", 1, /*wire=*/33, "MERGED CHAPATI"},
    {"Corrumpets",
     {{"self_signed_flour", 2}, {"double_precision_cream", 1}, {"c_salt", 1}},
     "corrumpets", 1, /*wire=*/34, "MERGED CORRUMPETS"},
    {"Packettone",
     {{"self_signed_flour", 2}, {"epoch_dates", 1}, {"syntactic_sugar", 1},
      {"churned_butter", 1}},
     "packettone", 1, /*wire=*/35, "MERGED PACKETTONE"},
    {"Hot-Swapped Buns",
     {{"self_signed_flour", 2}, {"cinnamon", 1}, {"syntactic_sugar", 1},
      {"churned_butter", 1}},
     "hot_swapped_buns", 1, /*wire=*/36, "MERGED HOT-SWAPPED BUNS"},
    {"Current Buns",
     {{"self_signed_flour", 2}, {"table_grapes", 2}, {"syntactic_sugar", 1}},
     "current_buns", 1, /*wire=*/37, "MERGED CURRENT BUNS"},
    {"Config Rolls",
     {{"dotfigs", 2}, {"self_signed_flour", 2}, {"syntactic_sugar", 1}},
     "config_rolls", 1, /*wire=*/38, "MERGED CONFIG ROLLS"},
    {"Crostini",
     {{"buguette", 1}, {"grepsed_oil", 1}, {"garlic_escapes", 1},
      {"bytesteak_tomatoes", 1}},
     "crostini", 1, /*wire=*/39, "MERGED CROSTINI"},
    {"Payloaf", {{"nan_bread", 1}, {"spam", 2}, {"c_salt", 1}},
     "payloaf", 1, /*wire=*/40, "MERGED PAYLOAF"},
    {"Firewaffle",
     {{"self_signed_flour", 2}, {"regeggs", 1}, {"churned_butter", 1},
      {"imaple_syrup", 1}},
     "firewaffle", 1, /*wire=*/41, "MERGED FIREWAFFLE"},
    // The pans.
    {"Chownder",
     {{"red_herring", 2}, {"polltatoes", 1}, {"perl_barley", 1},
      {"double_precision_cream", 1}},
     "chownder", 1, /*wire=*/42, "MERGED CHOWNDER"},
    {"Cronsomme",
     {{"boolean_cubes", 2}, {"parsenips", 1}, {"string_beans", 1}, {"c_salt", 1}},
     "cronsomme", 1, /*wire=*/43, "MERGED CRONSOMME"},
    {"WANton Soup",
     {{"self_signed_flour", 2}, {"minified_beef", 1}, {"snap_peas", 1},
      {"boolean_cubes", 1}},
     "wanton_soup", 1, /*wire=*/44, "MERGED WANTON SOUP"},
    {"Piperogi",
     {{"self_signed_flour", 2}, {"polltatoes", 2}, {"cruds", 1}, {"shellots", 1}},
     "piperogi", 1, /*wire=*/45, "MERGED PIPEROGI"},
    {"Queuesadilla",
     {{"nixtamal", 2}, {"mozillarella", 2}, {"flatpak_choi", 1}},
     "queuesadilla", 1, /*wire=*/46, "MERGED QUEUESADILLA"},
    {"Ravioli Code",
     {{"vpenne", 2}, {"squid_ink", 1}, {"cruds", 1}, {"paramesan", 1}},
     "ravioli_code", 1, /*wire=*/47, "MERGED RAVIOLI CODE"},
    {"Idleys",
     {{"basicmati_rice", 2}, {"lintils", 2}, {"c_salt", 1}},
     "idleys", 1, /*wire=*/48, "MERGED IDLEYS"},
    {"MS-Dosa",
     {{"basicmati_rice", 2}, {"lintils", 1}, {"grepsed_oil", 1},
      {"polltatoes", 1}},
     "ms_dosa", 1, /*wire=*/49, "MERGED MS-DOSA"},
    {"ARPas", {{"nixtamal", 2}, {"cruds", 1}, {"c_salt", 1}},
     "arpas", 1, /*wire=*/50, "MERGED ARPAS"},
    {"Kafkofta",
     {{"minified_beef", 1}, {"lambda_chops", 1}, {"breadcrumbs", 2},
      {"cinnamon", 1}},
     "kafkofta", 1, /*wire=*/51, "MERGED KAFKOFTA"},
    {"Kernel Panini",
     {{"buguette", 1}, {"mozillarella", 2}, {"bytesteak_tomatoes", 1}},
     "kernel_panini", 1, /*wire=*/52, "MERGED KERNEL PANINI"},
    {"Racelette",
     {{"mozillarella", 2}, {"polltatoes", 1}, {"kaliflower", 1}, {"gherkins", 1}},
     "racelette", 1, /*wire=*/53, "MERGED RACELETTE"},
    {"Scrambled RegEggs", {{"regeggs", 3}, {"churned_butter", 1}},
     "scrambled_regeggs", 1, /*wire=*/54, "MERGED SCRAMBLED REGEGGS"},
    {"Char-Grilled Array",
     {{"swiss_chard", 2}, {"bitroot", 1}, {"capsicum", 1}, {"grepsed_oil", 1}},
     "char_grilled_array", 1, /*wire=*/55, "MERGED CHAR-GRILLED ARRAY"},
    {"Tarballs",
     {{"minified_beef", 2}, {"breadcrumbs", 2}, {"grepsed_oil", 1}},
     "tarballs", 1, /*wire=*/56, "MERGED TARBALLS"},
    {"Bashed Potatoes",
     {{"polltatoes", 2}, {"squash", 1}, {"churned_butter", 1}},
     "bashed_potatoes", 1, /*wire=*/57, "MERGED BASHED POTATOES"},
    {"Onion Rings", {{"shellots", 3}, {"self_signed_flour", 1}},
     "onion_rings", 1, /*wire=*/58, "MERGED ONION RINGS"},
    {"Flash-Fried Chips",
     {{"polltatoes", 2}, {"plaintain", 1}, {"kernel_oil", 1}, {"c_salt", 1}},
     "flash_fried_chips", 1, /*wire=*/59, "MERGED FLASH-FRIED CHIPS"},
    {"Twisted Pairetzels",
     {{"self_signed_flour", 2}, {"chia_seeds", 1}, {"c_salt", 1}},
     "twisted_pairetzels", 1, /*wire=*/60, "MERGED TWISTED PAIRETZELS"},
    {"Jitter Fritters",
     {{"awkra", 2}, {"unmonitored_oats", 1}, {"grepsed_oil", 1}},
     "jitter_fritters", 1, /*wire=*/61, "MERGED JITTER FRITTERS"},
    {"SHAshimi", {{"red_herring", 2}, {"romaine", 1}, {"natto", 1}},
     "shashimi", 1, /*wire=*/62, "MERGED SHASHIMI"},
    // The plates.
    {"Spare RIBs",
     {{"saasage", 2}, {"imaple_syrup", 1}, {"capsicum", 1}, {"c_salt", 1}},
     "spare_ribs", 1, /*wire=*/63, "MERGED SPARE RIBS"},
    {"RESTed Steak",
     {{"file_mignon", 2}, {"churned_butter", 1}, {"peppermint", 1}},
     "rested_steak", 1, /*wire=*/64, "MERGED RESTED STEAK"},
    {"Privilege Escalope",
     {{"file_mignon", 2}, {"breadcrumbs", 2}, {"regeggs", 1}},
     "privilege_escalope", 1, /*wire=*/65, "MERGED PRIVILEGE ESCALOPE"},
    // Spam is pork, so the joke is the ingredient list: four tins, forced.
    {"Force-Pulled Pork", {{"spam", 4}, {"pwnzu_sauce", 1}},
     "force_pulled_pork", 1, /*wire=*/66, "MERGED FORCE-PULLED PORK"},
    {"Rubber Duck Confit",
     {{"rubber_ducks", 2}, {"kernel_oil", 2}, {"garlic_escapes", 1}},
     "rubber_duck_confit", 1, /*wire=*/67, "MERGED RUBBER DUCK CONFIT"},
    {"Vacuum-Sealed Leftovers",
     {{"tarballs", 1}, {"spam", 2}, {"gherkins", 1}},
     "vacuum_sealed_leftovers", 1, /*wire=*/68, "MERGED VACUUM-SEALED LEFTOVERS"},
    {"Disk Platter",
     {{"crostini", 1}, {"packed_sardines", 1}, {"archichoke", 1},
      {"paramesan", 1}},
     "disk_platter", 1, /*wire=*/69, "MERGED DISK PLATTER"},
    {"Serverless Platter",
     {{"cache_ews", 1}, {"macadamia", 1}, {"nibbles", 1}, {"silicon_wafers", 1}},
     "serverless_platter", 1, /*wire=*/70, "MERGED SERVERLESS PLATTER"},
    {"Pickle Jar", {{"gherkins", 3}, {"c_salt", 1}},
     "pickle_jar", 1, /*wire=*/71, "MERGED PICKLE JAR"},
    // The condiments.
    {"AI-oli",
     {{"garlic_escapes", 2}, {"regeggs", 1}, {"grepsed_oil", 2}},
     "ai_oli", 1, /*wire=*/72, "MERGED AI-OLI"},
    {"Vi-naigrette",
     {{"hard_cidr", 1}, {"grepsed_oil", 2}, {"c_salt", 1}},
     "vinaigrette", 1, /*wire=*/73, "MERGED VI-NAIGRETTE"},
    {"Malwarmalade", {{"grepefruit", 3}, {"syntactic_sugar", 2}},
     "malwarmalade", 1, /*wire=*/74, "MERGED MALWARMALADE"},
    {"Signal Jam", {{"cloudberries", 3}, {"syntactic_sugar", 2}},
     "signal_jam", 1, /*wire=*/75, "MERGED SIGNAL JAM"},
    // The puddings.
    {"POP3sicle", {{"pingapple", 2}, {"syntactic_sugar", 1}},
     "pop3sicle", 1, /*wire=*/76, "MERGED POP3SICLE"},
    {"Mergingue", {{"regeggs", 2}, {"syntactic_sugar", 2}},
     "mergingue", 1, /*wire=*/77, "MERGED MERGINGUE"},
    {"Declair",
     {{"self_signed_flour", 2}, {"double_precision_cream", 1}, {"cocoa", 1},
      {"regeggs", 1}},
     "declair", 1, /*wire=*/78, "MERGED DECLAIR"},
    {"Profilerole",
     {{"self_signed_flour", 2}, {"double_precision_cream", 2}, {"cocoa", 1}},
     "profilerole", 1, /*wire=*/79, "MERGED PROFILEROLE"},
    {"COBOLer",
     {{"apiricot", 2}, {"self_signed_flour", 2}, {"syntactic_sugar", 1}},
     "coboler", 1, /*wire=*/80, "MERGED COBOLER"},
    {"Clustard",
     {{"regeggs", 2}, {"double_precision_cream", 2}, {"vanilla_extract", 1}},
     "clustard", 1, /*wire=*/81, "MERGED CLUSTARD"},
    {"Bashlava",
     {{"macadamia", 2}, {"self_signed_flour", 2}, {"imaple_syrup", 1},
      {"churned_butter", 1}},
     "bashlava", 1, /*wire=*/82, "MERGED BASHLAVA"},
    {"Deflated Souffle", {{"regeggs", 3}, {"mozillarella", 1}},
     "deflated_souffle", 1, /*wire=*/83, "MERGED DEFLATED SOUFFLE"},
    {"Fork Bombe",
     {{"double_precision_cream", 2}, {"cocoa", 1}, {"marshalled_mallows", 1}},
     "fork_bombe", 1, /*wire=*/84, "MERGED FORK BOMBE"},
    {"Optical Mousse",
     {{"cocoa", 2}, {"double_precision_cream", 2}, {"regeggs", 1}},
     "optical_mousse", 1, /*wire=*/85, "MERGED OPTICAL MOUSSE"},
    {"Cherry-Picked Tart",
     {{"cloudberries", 2}, {"self_signed_flour", 2}, {"syntactic_sugar", 1}},
     "cherry_picked_tart", 1, /*wire=*/86, "MERGED CHERRY-PICKED TART"},
    {"Raspberry Pie",
     {{"raspberry_pis", 2}, {"self_signed_flour", 2}, {"syntactic_sugar", 1}},
     "raspberry_pie", 1, /*wire=*/87, "MERGED RASPBERRY PIE"},
    {"Rainbow Tablet",
     {{"syntactic_sugar", 2}, {"double_precision_cream", 1}, {"humbugs", 1},
      {"peer_drops", 1}},
     "rainbow_tablet", 1, /*wire=*/88, "MERGED RAINBOW TABLET"},
    {"Mint Choc Chip",
     {{"peppermint", 2}, {"cocoa", 1}, {"double_precision_cream", 2}},
     "mint_choc_chip", 1, /*wire=*/89, "MERGED MINT CHOC CHIP"},
    {"Candied YAMLs",
     {{"yamls", 2}, {"syntactic_sugar", 2}, {"churned_butter", 1}},
     "candied_yamls", 1, /*wire=*/90, "MERGED CANDIED YAMLS"},
    // What you drink with them.
    {"Flat White", {{"java", 2}, {"double_precision_cream", 1}},
     "flat_white", 1, /*wire=*/91, "MERGED FLAT WHITE"},
    {"Mockachino",
     {{"java", 1}, {"cocoa", 2}, {"double_precision_cream", 1}},
     "mockachino", 1, /*wire=*/92, "MERGED MOCKACHINO"},
    {"Blockchai",
     {{"leaf_node_tea", 2}, {"cinnamon", 1}, {"double_precision_cream", 1},
      {"syntactic_sugar", 1}},
     "blockchai", 1, /*wire=*/93, "MERGED BLOCKCHAI"},
    {"SYN-ACK Shake",
     {{"double_precision_cream", 2}, {"syntactic_sugar", 1},
      {"honeypot_yogurt", 1}},
     "syn_ack_shake", 1, /*wire=*/94, "MERGED SYN-ACK SHAKE"},
    {"Buffer Overfloat",
     {{"r007_b33r", 1}, {"double_precision_cream", 2}, {"syntactic_sugar", 1}},
     "buffer_overfloat", 1, /*wire=*/95, "MERGED BUFFER OVERFLOAT"},
    {"Hard CIDR", {{"applets", 3}, {"syntactic_sugar", 1}},
     "hard_cidr", 1, /*wire=*/96, "MERGED HARD CIDR"},
    {"Port 80", {{"table_grapes", 3}, {"syntactic_sugar", 1}},
     "port_80", 1, /*wire=*/97, "MERGED PORT 80"},
    {"FizzBuzz",
     {{"mixins", 2}, {"burp_sweets", 1}, {"syntactic_sugar", 1}},
     "fizzbuzz", 1, /*wire=*/98, "MERGED FIZZBUZZ"},
    {"Punchcard Punch",
     {{"pingapple", 1}, {"apiricot", 1}, {"mixins", 2}},
     "punchcard_punch", 1, /*wire=*/99, "MERGED PUNCHCARD PUNCH"},
};
const int kMergeRecipeCount =
    static_cast<int>(sizeof(kMergeRecipes) / sizeof(kMergeRecipes[0]));

}  // namespace mal
