// gen_demo_save.cpp — bakes the web demo's starting save blob.
//
// The web demo drops a visitor onto a raised pet with things to spend and systems
// already open, rather than onto the Decryption Hatch and a 30-minute incubation
// clock. That start state is expressed here as a SEED SCRIPT over the engine's own
// public API — install the pet, bank the XP, add the stacks, set the quote tiers —
// and then serialized through the real Game::saveNow(), so the blob is a save the
// device itself could have written.
//
// Output is a C++ byte array (src/generated/demo_save.cpp, declared by demo_save.h),
// compiled into the wasm target only. Nothing here links into firmware.
//
// Regenerated on every web build rather than committed, which is what keeps it from
// going stale: the blob is always produced by the engine that will read it, so
// kSaveVersion cannot drift out from under it. A committed blob would deserialize as
// EMPTY once the version moved past kOldestAcceptedVersion, and an empty save falls
// back to the Hatch — a demo that silently starts on an egg.
//
// Driven by tools/build_web.sh. Run standalone to inspect the blob:
//   cmake --build build --target gen_demo_save && ./build/gen_demo_save --print
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "core/app/game.h"
#include "core/model/cryptogram.h"
#include "platform/platform.h"

using namespace mal;

namespace {

// The seed's byte sink: Game::saveNow() writes through an ISaveStore like any other
// target, so the generator gets the blob by handing the engine somewhere to put it.
class MemSaveStore : public ISaveStore {
public:
    std::vector<uint8_t> load() override { return blob_; }
    bool save(const std::vector<uint8_t>& d) override { blob_ = d; return true; }
    void clear() override { blob_.clear(); }
    const std::vector<uint8_t>& blob() const { return blob_; }

private:
    std::vector<uint8_t> blob_;
};

// Which creature the visitor is handed. Cuttlefork is the Metamorphic line's first
// hatched stage and the most fully drawn process on the roster — four sculpts rather
// than a pose over one drawing (content/creatures/metamorphic/line.h) — so a demo that
// opens on it shows the habitat at its best rather than at its plainest.
constexpr const char* kSeedPetId = "cuttlefork";

// What the visitor starts holding. Enough of each kind that every screen the demo
// opens has something in it: food to feed with, buffs to read, and the Quest stack
// that is the DECRYPTOGRAM's ticket at the Hacker VAULT.
struct SeedStack { const char* id; int qty; };
constexpr SeedStack kSeedItems[] = {
    // Food — the FEED flow, and a spread wide enough that the ITEMS type filter has
    // something to filter.
    {"null_noodles", 6}, {"dyno_nuggets", 4}, {"spam", 5},
    {"polltatoes", 4},   {"java", 3},         {"linkguine", 3},
    // Buff — read on the detail screen, used pre-encounter.
    {"backdoor_bell", 2}, {"restore_point", 2}, {"deep_learning_module", 1},
    // Quest — decryptogram is the VAULT cash-in that opens a quote board, so the
    // demo carries a handful rather than one.
    {"decryptogram", 5}, {"sealed_cache", 2}, {"disk_scrubber", 2},
};

// Levels are banked as XP through the real addCombatXp path so the level-up's stat
// award runs exactly as it would in play — a demo pet whose statPoints_ sum matches
// its level, rather than a number written over the invariant.
constexpr int kSeedLevels = 6;

// Spending money. Enough to shop, gamble on a few arcade runs and still pay a
// Lockout out, without being so much that the economy stops being visible — a
// demo where nothing has a price teaches nothing about what things cost.
constexpr int kSeedBits = 2500;

// Quotes already cracked. kQuoteArcadeUnlockWins of them is what puts the
// DECRYPTOGRAM cabinet in the GAMES list (content_arcade.h's QuotesSolved gate), so
// the demo seeds exactly that many and leaves the rest of the pool to play for.
constexpr int kSeedSolvedQuotes = kQuoteArcadeUnlockWins;

void writeByteArray(FILE* f, const std::vector<uint8_t>& blob) {
    std::fprintf(f,
        "// GENERATED by tools/gen_demo_save.cpp — do not edit.\n"
        "// The web demo's starting save, serialized by the engine that reads it.\n"
        "#include \"generated/demo_save.h\"\n\n"
        "namespace mal {\n\n"
        "const unsigned char kDemoSaveBlob[] = {\n");
    for (size_t i = 0; i < blob.size(); ++i) {
        if (i % 12 == 0) std::fprintf(f, "   ");
        std::fprintf(f, " 0x%02x,", blob[i]);
        if (i % 12 == 11) std::fprintf(f, "\n");
    }
    if (blob.size() % 12 != 0) std::fprintf(f, "\n");
    std::fprintf(f, "};\n\nconst unsigned kDemoSaveBlobLen = %zuu;\n\n} // namespace mal\n",
                 blob.size());
}

void writeHeader(FILE* f) {
    std::fprintf(f,
        "// GENERATED by tools/gen_demo_save.cpp — do not edit.\n"
        "#pragma once\n\n"
        "namespace mal {\n\n"
        "// The web demo's starting save blob, in the wire format\n"
        "// core/model/save.h's deserializeSave() reads. Handed to the engine by\n"
        "// platform/web/save_store_web.h when localStorage holds nothing yet.\n"
        "extern const unsigned char kDemoSaveBlob[];\n"
        "extern const unsigned kDemoSaveBlobLen;\n\n"
        "} // namespace mal\n");
}

} // namespace

int main(int argc, char** argv) {
    std::string outDir = "src/generated";
    bool print = false;
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--print") == 0) print = true;
        else if (std::strcmp(argv[i], "--out") == 0 && i + 1 < argc) outDir = argv[++i];
    }

    MemSaveStore store;
    // StartMode::Hatched is the engine's own skip-the-egg seam: it installs the pet,
    // stamps its move slots and enforces the slot-kind invariant, so the seed starts
    // from a correctly-built pet rather than a hand-assembled one.
    Game game(StartMode::Hatched, kSeedPetId, &store);

    for (const SeedStack& s : kSeedItems) game.inventory().add(s.id, s.qty);

    // Each level costs round(kLevelXpBase * 1.1^level), so banking the ladder's own
    // cost per level is what advances exactly one level at a time.
    for (int lvl = 0; lvl < kSeedLevels; ++lvl) game.debugAddCombatXp(game.xpToNextLevel());

    game.debugSetBits(kSeedBits);

    const int quotes = quoteCount();
    for (int i = 0; i < kSeedSolvedQuotes && i < quotes; ++i)
        game.debugSetQuoteTier(i, CryptogramTier::Solved);

    if (!game.saveNow()) {
        std::fprintf(stderr, "gen_demo_save: saveNow() refused the seed\n");
        return 1;
    }
    const std::vector<uint8_t>& blob = store.blob();
    if (blob.empty()) {
        std::fprintf(stderr, "gen_demo_save: the store came back empty\n");
        return 1;
    }

    // Boot a second Game off the blob and check the seed survived the round trip.
    // A save the engine declines to read deserializes as EMPTY rather than failing,
    // and an empty save falls back to the Hatch — so without this the failure mode
    // is a demo that quietly starts on an egg. Fail the build here instead.
    {
        // The pet install grants its own starting stacks, so the expected count is
        // whatever the seeded game actually holds, not the length of kSeedItems.
        const size_t seededStacks = game.inventory().stacks().size();
        Game restored(StartMode::FreshHatch, kSeedPetId, &store);
        const bool ok =
            restored.pet() && std::strcmp(restored.pet()->id, kSeedPetId) == 0 &&
            restored.combatLevel() == kSeedLevels &&
            restored.bits() == kSeedBits &&
            restored.quotesSolved() >= kSeedSolvedQuotes &&
            restored.inventory().stacks().size() == seededStacks;
        if (!ok) {
            std::fprintf(stderr,
                "gen_demo_save: the blob did not round-trip\n"
                "  pet    %s\n  level  %d (want %d)\n  bits   %d (want %d)\n"
                "  quotes %d (want >= %d)\n  stacks %zu (want %zu)\n",
                restored.pet() ? restored.pet()->id : "(none)",
                restored.combatLevel(), kSeedLevels, restored.bits(), kSeedBits,
                restored.quotesSolved(), kSeedSolvedQuotes,
                restored.inventory().stacks().size(), seededStacks);
            return 1;
        }
    }

    if (print) {
        std::printf("demo save: %zu bytes\n", blob.size());
        std::printf("  pet       %s\n", game.pet() ? game.pet()->displayName : "(none)");
        std::printf("  level     %d (xp %d)\n", game.combatLevel(), game.combatXp());
        std::printf("  bits      %d\n", game.bits());
        std::printf("  stacks    %zu\n", game.inventory().stacks().size());
        std::printf("  quotes    %d solved of %d\n", game.quotesSolved(), quotes);
        return 0;
    }

    const std::string cpp = outDir + "/demo_save.cpp";
    const std::string hdr = outDir + "/demo_save.h";
    FILE* f = std::fopen(cpp.c_str(), "wb");
    if (!f) { std::fprintf(stderr, "gen_demo_save: cannot write %s\n", cpp.c_str()); return 1; }
    writeByteArray(f, blob);
    std::fclose(f);
    f = std::fopen(hdr.c_str(), "wb");
    if (!f) { std::fprintf(stderr, "gen_demo_save: cannot write %s\n", hdr.c_str()); return 1; }
    writeHeader(f);
    std::fclose(f);

    std::printf("wrote %s (%zu bytes of save)\n", cpp.c_str(), blob.size());
    return 0;
}
